#!/usr/bin/env perl

use strict;
use 5.008001;
use TableMerge;

exit TableMerge->new->run(@ARGV);

__END__

=head1 NAME

tablemerge

=head1 SYNOPSIS

  > tablemerge MYFILE OLDFILE YOURFILE

=head1 DESCRIPTION


=head1 SEE ALSO

L<TableMerge>

=cut
