#!/usr/bin/env perl

use strict;
use 5.008001;
use TableMerge::Resolve;

exit TableMerge::Resolve->new->run(@ARGV);

__END__

=head1 NAME

tablemergeresolve

=head1 SYNOPSIS

  > tablemergeresolve CONFLICTFILE

=head1 DESCRIPTION


=head1 SEE ALSO

L<TableMerge>

=cut
